name: Restrict PR Source to Dev

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          echo "🔍 Checking source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "PR to main is only allowed from 'dev' branch."
            exit 1
          fi
          echo "Valid PR from 'dev' branch."
